let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Dolo 650",
    price: 30,
    desc: "Strip of 15 tablets",
    img: "images/card-images/pc.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Cetrizine Tablet",
    price: 30,
    desc: "Strip of 15 tablets",
    img: "images/card-images/cetrizine.jpeg",
  },
  {
    id: "wuefbncxbsn",
    name: "Vitamin-C Tablet",
    price: 540,
    desc: "Box of 120 tablets",
    img: "images/card-images/vitaminc.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Vitamin-D Tablet",
    price: 150,
    desc: "Strip of 15 tablets",
    img: "images/card-images/cd3.jpg",
  },
  {
    id: "jfhgbvnsce",
    name: "Ear Drops",
    price: 30,
    desc: "Bottle of 10ml ear drops",
    img: "images/ear.jpg",
  },
  {
    id: "ioytrhndce",
    name: "Cetrizine Tablet",
    price: 30,
    desc: "Strip of 15 tablets",
    img: "images/citrizene.jpg",
  },
  {
    id: "wuefbncxbse",
    name: "Vitamin-C Tablet",
    price: 540,
    desc: "Bottle of 120 tablets",
    img: "images/vitaminc.jpg",
  },
  {
    id: "thyfhcbce",
    name: "Asprin 750mg",
    price: 300,
    desc: "Strip of 15 tablets",
    img: "images/card-images/asprin.webp",
  },
  {
    id: "jfhgbvnsca",
    name: "Vitamin-e capsules",
    price: 30,
    desc: "Strip of 15 tablets",
    img: "images/card-images/vitamine.jpg",
  },
  {
    id: "ioytrhndca",
    name: "Insulin",
    price: 100,
    desc: "10ml Insulin Bottle",
    img: "images/card-images/insulin.jpg",
  },
  {
    id: "wuefbncxbsa",
    name: "Vitamin-b12",
    price: 140,
    desc: "Bottle of 120 tablets",
    img: "images/b12.jpg",
  },
  {
    id: "thyfhcbca",
    name: "Pain Killer",
    price: 30,
    desc: "Strip of 15 tablets",
    img: "images/painkiller.jpg",
  },
  {
    id: "jfhgbvnscb",
    name: "Pain Relif Gel",
    price: 100,
    desc: "50g tube",
    img: "images/pain-relif.jpg",
  },
  {
    id: "ioytrhndcb",
    name: "Betadin Ointment",
    price: 100,
    desc: "50g tube",
    img: "images/betadin.jpg",
  },
  {
    id: "wuefbncxbsb",
    name: "Hansaplast",
    price: 30,
    desc: "Bandages Pack of 20",
    img: "images/bandage.jpg",
  },
  {
    id: "thyfhcbcb",
    name: "Milamin Capsule",
    price: 50,
    desc: "Strip of 15 capsules",
    img: "images/mylamin-capsule.jpg",
  },
];
